test:
	#pytest --rootdir=U:\src\PreREISE\prereise\gather\demanddata\EIA\ --continue-on-collection-errors --maxfail=10 test_from_excel.py
	#pytest --rootdir=U:\src\PreREISE\prereise\gather\demanddata\EIA\ --continue-on-collection-errors --maxfail=10 test_EIAdownload.py
	#this works better since python puts current dir into sys.path, while pytest requires a requirements.txt file
	python -m pytest
