nhts_census_column_names = [
    "Household",
    "Vehicle ID",
    "Person ID",
    "Scaling Factor Applied",
    "Trip Number",
    "Date",
    "Day of Week",
    "If Weekend",
    "Trip start time (HHMM)",
    "Trip end time (HHMM)",
    "Travel Minutes",
    "Dwell time",
    "Miles traveled",
    "Vehicle miles traveled",
    "why from",
    "why to",
    "Vehicle type",
    "Household vehicle count",
    "Household size",
    "Trip type",
    "Start time (hour decimal)",
    "End time (hour decimal)",
    "Dwell time (hour decimal)",
    "Travel time (hour decimal)",
    "Vehicle speed (mi/hour)",
    "sample vehicle number",
    "total vehicle trips",
    "total vehicle miles traveled",
]
