# Map state abbreviations to state name
abv2state = {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
}

lower_48_states_abv = list(abv2state.keys())
lower_48_states_abv.remove("AK")
lower_48_states_abv.remove("HI")

zone2state_abv = {
    "Alabama": "AL",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "Bay Area": "CA",
    "Central California": "CA",
    "Chicago North Illinois": "IL",
    "Coast": "TX",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "East": "TX",
    "East Texas": "TX",
    "El Paso": "TX",
    "Far West": "TX",
    "Florida North": "FL",
    "Florida Panhandle": "FL",
    "Florida South": "FL",
    "Georgia North": "GA",
    "Georgia South": "GA",
    "Idaho": "ID",
    "Illinois Downstate": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan Northern": "MI",
    "Michigan Southern": "MI",
    "Minnesota Northern": "MN",
    "Minnesota Southern": "MN",
    "Mississippi": "MS",
    "Missouri East": "MO",
    "Missouri West": "MO",
    "Montana Eastern": "MT",
    "Montana Western": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico Eastern": "NM",
    "New Mexico Western": "NM",
    "New York City": "NY",
    "North": "TX",
    "North Carolina": "NC",
    "North Central": "TX",
    "North Dakota": "ND",
    "Northern California": "CA",
    "Ohio Lake Erie": "OH",
    "Ohio River": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania Eastern": "PA",
    "Pennsylvania Western": "PA",
    "Rhode Island": "RI",
    "South": "TX",
    "South Carolina": "SC",
    "South Central": "TX",
    "South Dakota": "SD",
    "Southeast California": "CA",
    "Southwest California": "CA",
    "Tennessee": "TN",
    "Texas Panhandle": "TX",
    "Upstate New York": "NY",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia Mountains": "VA",
    "Virginia Tidewater": "VA",
    "Washington": "WA",
    "West": "TX",
    "West Virginia": "WV",
    "Western North Carolina": "NC",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}
