import os

import numpy as np
import pandas as pd

state_list = [
    "AL",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
]

zone_names = [
    "NYIS-ZONA",  # NYISO
    "NYIS-ZONB",
    "NYIS-ZONC",
    "NYIS-ZOND",
    "NYIS-ZONE",
    "NYIS-ZONF",
    "NYIS-ZONG",
    "NYIS-ZONH",
    "NYIS-ZONI",
    "NYIS-ZONJ",
    "NYIS-ZONK",
    "ERCO-C",  # ERCOT
    "ERCO-E",
    "ERCO-FW",
    "ERCO-N",
    "ERCO-NC",
    "ERCO-S",
    "ERCO-SC",
    "ERCO-W",
    "CISO-PGAE",  # CAISO
    "CISO-SCE",
    "CISO-SDGE",
    "CISO-VEA",
    "IID",
    "WALC",
    "LDWP",
    "TIDC",
    "BANC",
    "ISNE-4000",  # ISO-NE
    "ISNE-4001",
    "ISNE-4002",
    "ISNE-4003",
    "ISNE-4004",
    "ISNE-4005",
    "PJM-AE",  # PJM
    "PJM-AEP",
    "PJM-AP",
    "PJM-ATSI",
    "PJM-BC",
    "PJM-CE",
    "PJM-DAY",
    "PJM-DEOK",
    "PJM-DUQ",
    "PJM-DPL",
    "PJM-DOM",
    "PJM-EKPC",
    "PJM-JC",
    "PJM-ME",
    "PJM-PE",
    "PJM-PN",
    "PJM-PEP",
    "PJM-PL",
    "PJM-PS",
    "PJM-RECO",
    "SWPP-CSWS",  # SPP
    "SWPP-EDE",
    "SWPP-GRDA",
    "SWPP-KACY",
    "SWPP-KCPL",
    "SWPP-LES",
    "SWPP-MPS",
    "SWPP-NPPD",
    "SWPP-OKGE",
    "SWPP-OPPD",
    "SWPP-SECI",
    "SWPP-SPRM",
    "SWPP-SPS",
    "SWPP-WAUE",
    "SWPP-WFEC",
    "SWPP-WR",
    "MISO-0001",  # MISO
    "MISO-0004",
    "MISO-0006",
    "MISO-0027",
    "MISO-0035",
    "MISO-8910",
    "PNM",  # Southwest
    "EPE",
    "TEPC",
    "AZPS",
    "WACM",
    "PACE",
    "PSCO",
    "PSEI",  # Northwest
    "DOPD",
    "AVA",
    "CHPD",
    "GCPD",
    "BPAT",
    "PGE",
    "PACW",
    "IPCO",
    "NWMT",
    "NEVP",
    "AECI",  # Southeast
    "SOCO",
    "AEC",
    "TVA",
    "Carolina",
    "Florida",
]

zone_name_shps = [
    "NYISO-A",  # NYISO
    "NYISO-B",
    "NYISO-C",
    "NYISO-D",
    "NYISO-E",
    "NYISO-F",
    "NYISO-G",
    "NYISO-H",
    "NYISO-I",
    "NYISO-J",
    "NYISO-K",
    "ERCO-C",  # ERCOT
    "ERCO-E",
    "ERCO-FW",
    "ERCO-N",
    "ERCO-NC",
    "ERCO-S",
    "ERCO-SC",
    "ERCO-W",
    "CISO-PGAE",  # CAISO
    "CISO-SCE",
    "CISO-SDGE",
    "CISO-VEA",
    "IID",
    "WALC",
    "LADWP",
    "TID",
    "BANC",
    "ISONE-Massachusetts",  # ISO-NE
    "ISONE-Maine",
    "ISONE-New Hampshire",
    "ISONE-Vermont",
    "ISONE-Connecticut",
    "ISONE-Rhode Island",
    "PJM_AE",  # PJM
    "PJM_AEP",
    "PJM_AP",
    "PJM_ATSI",
    "PJM_BGE",
    "PJM_ComEd",
    "PJM_DAY",
    "PJM_DEO&K",
    "PJM_DLCO",
    "PJM_DP&L",
    "PJM_Dominion",
    "PJM_EKPC",
    "PJM_JCP&L",
    "PJM_METED",
    "PJM_PECO",
    "PJM_PENELEC",
    "PJM_PEPCO",
    "PJM_PPL",
    "PJM_PSEG",
    "PJM_RECO",
    "SPP-CSWS",  # SPP
    "SPP-EDE",
    "SPP-GRDA",
    "SPP-KACY",
    "SPP-KCPL",
    "SPP-LES",
    "SPP-MPS",
    "SPP-NPPD",
    "SPP-OKGE",
    "SPP-OPPD",
    "SPP-SECI",
    "SPP-SPRM",
    "SPP-SPS",
    "SPP-WAUE",
    "SPP-WFEC",
    "SPP-WR",
    "MISO-0001",  # MISO
    "MISO-0004",
    "MISO-0006",
    "MISO-0027",
    "MISO-0035",
    "MISO-8910",
    "PNM",  # Southwest
    "EPE",
    "TEPC",
    "Arizona",
    "WACM",
    "PACE",
    "PSCO",
    "PSEI",  # Northwest
    "DOPD",
    "AVA",
    "CHPD",
    "GCPD",
    "BPAT",
    "PGE",
    "PACW",
    "IPCO",
    "MT_west",
    "NEVP",
    "AECI",  # Southeast
    "SOCO",
    "AEC",
    "TVA",
    "Carolina",
    "Florida",
]

iso_name = {
    "NY": "New York",
    "TX": "Texas",
    "CA": "California",
    "NE": "New England",
    "PJM": "PJM Interconnection",
    "SPP": "Southwest Power Pool",
    "MISO": "Midcontinent ISO",
    "SW": "Southwest",
    "NW": "Northwest",
    "SE": "Southeast",
    "USA": "United States",
    "Outliers": "Model Outliers",
}

iso_zone_names = {
    "NY": [
        "NYIS-ZONA",
        "NYIS-ZONB",
        "NYIS-ZONC",
        "NYIS-ZOND",
        "NYIS-ZONE",
        "NYIS-ZONF",
        "NYIS-ZONG",
        "NYIS-ZONH",
        "NYIS-ZONI",
        "NYIS-ZONJ",
        "NYIS-ZONK",
    ],
    "TX": [
        "ERCO-C",
        "ERCO-E",
        "ERCO-FW",
        "ERCO-N",
        "ERCO-NC",
        "ERCO-S",
        "ERCO-SC",
        "ERCO-W",
    ],
    "CA": [
        "CISO-PGAE",
        "CISO-SCE",
        "CISO-SDGE",
        "IID",
        "WALC",
        "LDWP",
        "TIDC",
        "BANC",
    ],
    "NE": [
        "ISNE-4000",
        "ISNE-4001",
        "ISNE-4002",
        "ISNE-4003",
        "ISNE-4004",
        "ISNE-4005",
    ],
    "PJM": [
        "PJM-AE",
        "PJM-AEP",
        "PJM-AP",
        "PJM-ATSI",
        "PJM-BC",
        "PJM-CE",
        "PJM-DAY",
        "PJM-DEOK",
        "PJM-DUQ",
        "PJM-DPL",
        "PJM-DOM",
        "PJM-EKPC",
        "PJM-JC",
        "PJM-ME",
        "PJM-PE",
        "PJM-PN",
        "PJM-PEP",
        "PJM-PL",
        "PJM-PS",
        "PJM-RECO",
    ],
    "SPP": [
        "SWPP-CSWS",
        "SWPP-EDE",
        "SWPP-GRDA",
        "SWPP-KACY",
        "SWPP-KCPL",
        "SWPP-LES",
        "SWPP-MPS",
        "SWPP-NPPD",
        "SWPP-OKGE",
        "SWPP-OPPD",
        "SWPP-SECI",
        "SWPP-SPRM",
        "SWPP-SPS",
        "SWPP-WAUE",
        "SWPP-WFEC",
        "SWPP-WR",
    ],
    "MISO": [
        "MISO-0001",
        "MISO-0004",
        "MISO-0006",
        "MISO-0027",
        "MISO-0035",
        "MISO-8910",
    ],
    "SW": [
        "PNM",
        "EPE",
        "TEPC",
        "AZPS",
        "WACM",
        "PACE",
        "PSCO",
    ],
    "NW": [
        "PSEI",
        "DOPD",
        "AVA",
        "CHPD",
        "GCPD",
        "BPAT",
        "PGE",
        "PACW",
        "IPCO",
        "NWMT",
        "NEVP",
    ],
    "SE": [
        "AECI",
        "SOCO",
        "AEC",
        "TVA",
        "Carolina",
        "Florida",
    ],
    "USA": [
        "NYIS-ZONA",
        "NYIS-ZONB",
        "NYIS-ZONC",
        "NYIS-ZOND",
        "NYIS-ZONE",
        "NYIS-ZONF",
        "NYIS-ZONG",
        "NYIS-ZONH",
        "NYIS-ZONI",
        "NYIS-ZONJ",
        "NYIS-ZONK",
        "ERCO-C",
        "ERCO-E",
        "ERCO-FW",
        "ERCO-N",
        "ERCO-NC",
        "ERCO-S",
        "ERCO-SC",
        "ERCO-W",
        "CISO-PGAE",
        "CISO-SCE",
        "CISO-SDGE",
        "IID",
        "WALC",
        "LDWP",
        "TIDC",
        "BANC",
        "ISNE-4000",
        "ISNE-4001",
        "ISNE-4002",
        "ISNE-4003",
        "ISNE-4004",
        "ISNE-4005",
        "PJM-AE",
        "PJM-AEP",
        "PJM-AP",
        "PJM-ATSI",
        "PJM-BC",
        "PJM-CE",
        "PJM-DAY",
        "PJM-DEOK",
        "PJM-DUQ",
        "PJM-DPL",
        "PJM-DOM",
        "PJM-EKPC",
        "PJM-JC",
        "PJM-ME",
        "PJM-PE",
        "PJM-PN",
        "PJM-PEP",
        "PJM-PL",
        "PJM-PS",
        "PJM-RECO",
        "SWPP-CSWS",
        "SWPP-EDE",
        "SWPP-GRDA",
        "SWPP-KACY",
        "SWPP-KCPL",
        "SWPP-LES",
        "SWPP-MPS",
        "SWPP-NPPD",
        "SWPP-OKGE",
        "SWPP-OPPD",
        "SWPP-SECI",
        "SWPP-SPRM",
        "SWPP-SPS",
        "SWPP-WAUE",
        "SWPP-WFEC",
        "SWPP-WR",
        "MISO-0001",
        "MISO-0004",
        "MISO-0006",
        "MISO-0027",
        "MISO-0035",
        "MISO-8910",
        "PNM",
        "EPE",
        "TEPC",
        "AZPS",
        "WACM",
        "PACE",
        "PSCO",
        "PSEI",
        "DOPD",
        "AVA",
        "CHPD",
        "GCPD",
        "BPAT",
        "PGE",
        "PACW",
        "IPCO",
        "NWMT",
        "NEVP",
        "AECI",
        "SOCO",
        "AEC",
        "TVA",
        "Carolina",
        "Florida",
    ],
    "Outliers": [
        "NYIS-ZOND",
        "NYIS-ZONH",
        "WALC",
        "PJM-RECO",
        "SWPP-WFEC",
        "PSEI",
        "AECI",
    ],
}

iso_zone_name_shps = {
    "NY": [
        "NYISO-A",
        "NYISO-B",
        "NYISO-C",
        "NYISO-D",
        "NYISO-E",
        "NYISO-F",
        "NYISO-G",
        "NYISO-H",
        "NYISO-I",
        "NYISO-J",
        "NYISO-K",
    ],
    "TX": [
        "ERCO-C",
        "ERCO-E",
        "ERCO-FW",
        "ERCO-N",
        "ERCO-NC",
        "ERCO-S",
        "ERCO-SC",
        "ERCO-W",
    ],
    "CA": [
        "CISO-PGAE",
        "CISO-SCE",
        "CISO-SDGE",
        "IID",
        "WALC",
        "LADWP",
        "TID",
        "BANC",
    ],
    "NE": [
        "ISONE-Massachusetts",
        "ISONE-Maine",
        "ISONE-New Hampshire",
        "ISONE-Vermont",
        "ISONE-Connecticut",
        "ISONE-Rhode Island",
    ],
    "PJM": [
        "PJM_AE",
        "PJM_AEP",
        "PJM_AP",
        "PJM_ATSI",
        "PJM_BGE",
        "PJM_ComEd",
        "PJM_DAY",
        "PJM_DEO&K",
        "PJM_DLCO",
        "PJM_DP&L",
        "PJM_Dominion",
        "PJM_EKPC",
        "PJM_JCP&L",
        "PJM_METED",
        "PJM_PECO",
        "PJM_PENELEC",
        "PJM_PEPCO",
        "PJM_PPL",
        "PJM_PSEG",
        "PJM_RECO",
    ],
    "SPP": [
        "SPP-CSWS",
        "SPP-EDE",
        "SPP-GRDA",
        "SPP-KACY",
        "SPP-KCPL",
        "SPP-LES",
        "SPP-MPS",
        "SPP-NPPD",
        "SPP-OKGE",
        "SPP-OPPD",
        "SPP-SECI",
        "SPP-SPRM",
        "SPP-SPS",
        "SPP-WAUE",
        "SPP-WFEC",
        "SPP-WR",
    ],
    "MISO": [
        "MISO-0001",
        "MISO-0004",
        "MISO-0006",
        "MISO-0027",
        "MISO-0035",
        "MISO-8910",
    ],
    "SW": [
        "PNM",
        "EPE",
        "TEPC",
        "Arizona",
        "WACM",
        "PACE",
        "PSCO",
    ],
    "NW": [
        "PSEI",
        "DOPD",
        "AVA",
        "CHPD",
        "GCPD",
        "BPAT",
        "PGE",
        "PACW",
        "IPCO",
        "MT_west",
        "NEVP",
    ],
    "SE": [
        "AECI",
        "SOCO",
        "AEC",
        "TVA",
        "Carolina",
        "Florida",
    ],
    "USA": [
        "NYISO-A",
        "NYISO-B",
        "NYISO-C",
        "NYISO-D",
        "NYISO-E",
        "NYISO-F",
        "NYISO-G",
        "NYISO-H",
        "NYISO-I",
        "NYISO-J",
        "NYISO-K",
        "ERCO-C",
        "ERCO-E",
        "ERCO-FW",
        "ERCO-N",
        "ERCO-NC",
        "ERCO-S",
        "ERCO-SC",
        "ERCO-W",
        "CISO-PGAE",
        "CISO-SCE",
        "CISO-SDGE",
        "IID",
        "WALC",
        "LADWP",
        "TID",
        "BANC",
        "ISONE-Massachusetts",
        "ISONE-Maine",
        "ISONE-New Hampshire",
        "ISONE-Vermont",
        "ISONE-Connecticut",
        "ISONE-Rhode Island",
        "PJM_AE",
        "PJM_AEP",
        "PJM_AP",
        "PJM_ATSI",
        "PJM_BGE",
        "PJM_ComEd",
        "PJM_DAY",
        "PJM_DEO&K",
        "PJM_DLCO",
        "PJM_DP&L",
        "PJM_Dominion",
        "PJM_EKPC",
        "PJM_JCP&L",
        "PJM_METED",
        "PJM_PECO",
        "PJM_PENELEC",
        "PJM_PEPCO",
        "PJM_PPL",
        "PJM_PSEG",
        "PJM_RECO",
        "SPP-CSWS",
        "SPP-EDE",
        "SPP-GRDA",
        "SPP-KACY",
        "SPP-KCPL",
        "SPP-LES",
        "SPP-MPS",
        "SPP-NPPD",
        "SPP-OKGE",
        "SPP-OPPD",
        "SPP-SECI",
        "SPP-SPRM",
        "SPP-SPS",
        "SPP-WAUE",
        "SPP-WFEC",
        "SPP-WR",
        "MISO-0001",
        "MISO-0004",
        "MISO-0006",
        "MISO-0027",
        "MISO-0035",
        "MISO-8910",
        "PNM",
        "EPE",
        "TEPC",
        "Arizona",
        "WACM",
        "PACE",
        "PSCO",
        "PSEI",
        "DOPD",
        "AVA",
        "CHPD",
        "GCPD",
        "BPAT",
        "PGE",
        "PACW",
        "IPCO",
        "MT_west",
        "NEVP",
        "AECI",
        "SOCO",
        "AEC",
        "TVA",
        "Carolina",
        "Florida",
    ],
    "Outliers": [
        "NYISO-D",
        "NYISO-H",
        "WALC",
        "PJM_RECO",
        "SPP-WFEC",
        "PSEI",
        "AECI",
    ],
}

classes = ["res", "com"]

# Years with temperature data
yr_temps_all = list(range(1950, 2021))
yr_temps_first, yr_temps_last = yr_temps_all[0], yr_temps_all[-1]

# COP and capacity ratio models based on:
# (a) 50th percentile NEEP CCHP database [midperfhp],
# (b) 90th percentile NEEP CCHP database [advperfhp],
# (c) future HP targets, average of residential and commercial targets [futurehp]
dir_path = os.path.dirname(os.path.abspath(__file__))
hp_param = pd.read_csv(os.path.join(dir_path, "data", "hp_parameters.csv"))
hp_param_dhw = pd.read_csv(os.path.join(dir_path, "data", "hp_parameters_dhw.csv"))
puma_data = pd.read_csv(
    os.path.join(dir_path, "data", "puma_data.csv"), index_col="puma"
)
puma_fuel = pd.read_csv(
    os.path.join(dir_path, "data", "puma_fuel.csv"), index_col="puma"
)

# Reference temperatures for computations
temp_ref = {"res": 18.3, "com": 16.7}

# Unit conversions
conv_kw_to_mw = 1 / 1000  # Convert kW to MW
conv_mmbtu_to_kwh = 293.0711  # Convert MMBtu (million Btu) to kWh
conv_m2_to_ft2 = 1 / (0.3048**2)  # Convert square meters to square feet
conv_ft2_to_bsf = 1 / (10**9)  # Convert square feet to billion square feet
conv_mw_to_btu = 3412141  # Convert MW to Btu

eff_htg_ff_base = 0.80  # Assumed efficiency of existing fossil fuel HTG
eff_dhw_ff_base = 0.58  # Assumed efficiency of existing fossil fuel DHW

dhw_res_mult = [
    0.049666,
    0.020822,
    0.043178,
    0.040899,
    0.042389,
    0.653633,
    1.779551,
    2.715222,
    2.237019,
    1.265490,
    0.902268,
    0.995814,
    1.076690,
    0.878641,
    0.895299,
    0.973195,
    1.002082,
    0.957677,
    1.230816,
    1.858849,
    1.783014,
    1.219244,
    0.897841,
    0.480701,
]

dhw_com_mult = [1] * 24  # placeholder in case we need a multiplier for commercial

# Cooking efficiency multipliers
cooking_multiplier = {
    ("com", "low"): 0.46,
    ("com", "high"): 0.4,
    ("res", "low"): 0.44,
    ("res", "high"): 0.26,
}

# Setting res hot water slope as 0.01x res hot water const
dhw_lin_scalar = 0.01

bounds_lower_res = [0, 0.00000959, 0.00000269]
bounds_upper_res = [np.inf, 0.00001827, 0.00000864]

# Setting com cooking const as 1.5x com hot water const
cook_c_scalar = 1.5

dhw_low_bound_com = 0.00000796
dhw_high_bound_com = 0.00001858

other_high_bound_com = 0.00000228

recs_date_1 = 2009
recs_date_2 = 2015

cbecs_date_1 = 2012
cbecs_date_2 = 2018

base_year = 2019

# Regions to differentiate fuel usage: NorthEast, MidWest, South, West. Defined by RECS/CBECS surveys
regions = {
    "northeast": ["CT", "MA", "ME", "NH", "NJ", "NY", "PA", "RI", "VT"],
    "midwest": ["IA", "IL", "IN", "KS", "MI", "MN", "MO", "ND", "NE", "OH", "SD", "WI"],
    "south": [
        "AL",
        "AR",
        "DC",
        "DE",
        "FL",
        "GA",
        "KY",
        "LA",
        "MD",
        "MS",
        "NC",
        "OK",
        "SC",
        "TN",
        "TX",
        "VA",
        "WV",
    ],
    "west": [
        "AK",
        "AZ",
        "CA",
        "CO",
        "HI",
        "ID",
        "MT",
        "NM",
        "NV",
        "OR",
        "UT",
        "WA",
        "WY",
    ],
}

fuel = ["natgas", "fok", "othergas", "elec"]

# census region for current heat pump penetration. Defined by RECS/CBECS surveys
census_region = {
    "res": {
        "New England": ["MA", "CT", "ME", "NH", "RI", "VT"],
        "Middle Atlantic": ["NJ", "NY", "PA"],
        "East North Central": ["IL", "MI", "WI", "IN", "OH"],
        "West North Central": ["MO", "IA", "MN", "ND", "SD", "KS", "NE"],
        "South Atlantic": ["VA", "GA", "FL", "DC", "DE", "MD", "WV", "NC", "SC"],
        "East South Central": ["TN", "AL", "KY", "MS"],
        "West South Central": ["TX", "AR", "LA", "OK"],
        "Mountain North": ["CO", "ID", "MT", "UT", "WY"],
        "Mountain South": ["AZ", "NM", "NV"],
        "Pacific": ["CA", "AK", "HI", "OR", "WA"],
    },
    "com": {
        "New England": ["MA", "CT", "ME", "NH", "RI", "VT"],
        "Middle Atlantic": ["NJ", "NY", "PA"],
        "East North Central": ["IL", "MI", "WI", "IN", "OH"],
        "West North Central": ["MO", "IA", "MN", "ND", "SD", "KS", "NE"],
        "South Atlantic": ["VA", "GA", "FL", "DC", "DE", "MD", "WV", "NC", "SC"],
        "East South Central": ["TN", "AL", "KY", "MS"],
        "West South Central": ["TX", "AR", "LA", "OK"],
        "Mountain": ["CO", "ID", "MT", "UT", "WY", "AZ", "NM", "NV"],
        "Pacific": ["CA", "AK", "HI", "OR", "WA"],
    },
}
