name: Lint

on: [push, pull_request]

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@master
