name: Code coverage

on:
  push:
    branches:
      - 'develop'

jobs:
  coverage:
    runs-on: ubuntu-latest

    name: Generate coverage report
    steps:
      - name: Checkout PreREISE
        uses: actions/checkout@v2
        with:
          path: PreREISE

      - name: Checkout PowerSimData
        uses: actions/checkout@v2
        with:
          repository: Breakthrough-Energy/PowerSimData
          path: PowerSimData

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: python -m pip install --upgrade pip tox
        working-directory: PreREISE

      - run: tox -e pytest-local -- --cov-report=xml
        working-directory: PreREISE

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-prereise
          fail_ci_if_error: true
          directory: PreREISE
