name: Trigger external workflows

on:
  push:
    branches:
      - develop

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish docs website
        uses: Breakthrough-Energy/actions/workflow-trigger@main
        with:
          repo: docs
          branch: master
          workflow_id: 2386877
          token: ${{ secrets.CI_TOKEN_CLONE_REPO }}
