name: Pytest

on: push

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    name: Python ${{ matrix.python-version }}
    steps:
      - name: Checkout PreREISE
        uses: actions/checkout@v2
        with:
          path: PreREISE

      - name: Checkout PowerSimData
        uses: actions/checkout@v2
        with:
          repository: Breakthrough-Energy/PowerSimData
          token: ${{ secrets.CI_TOKEN_CLONE_REPO }}
          path: PowerSimData

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: python -m pip install --upgrade tox
        working-directory: PreREISE

      - run: tox -e pytest-local
        working-directory: PreREISE
